#!/bin/sh

#free --mebi | sed -n '2{p;q}' | awk '{printf ("%2.2fGiB\n", ( $3 / 1024))}'
#free -h | sed 's/,/./g' | sed 's/Mi/M/g' | sed 's/Gi/G/g' | awk '/^Mem:/ {print $3 "/" $2}'
free -h | sed 's/,/./g' | sed 's/Mi/M/g' | awk '/^Mem:/ {print $3}'
